server:
  port: 8090


# 配置数据基本信息
spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
